name: Deployanje na DockerHub

# Proženje po uspešnem zaključku testiranja
on:
  workflow_run:
    workflows: ['Testiranje projekta']
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    environment: production # Okolje za produkcijo
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Zažene se le ob uspehu testov
    strategy:
      matrix:
        component: [server, client] # Matrika za server in client
    steps:
      # Kloniranje repozitorija
      - name: Checkout koda
        uses: actions/checkout@v4

      # Prijava v DockerHub
      - name: Prijava v DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Gradnja Docker slike
      - name: Zgradi Docker sliko za ${{ matrix.component }}
        run: |
          docker build ${{ matrix.component == 'server' && 'Server' || 'Client' }}/ \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.component }}_sa_webcam:latest

      # Potiskanje Docker slike
      - name: Potisni Docker sliko za ${{ matrix.component }}
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.component }}_sa_webcam:latest
